apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: mod-chart
version: 1.0.0
home: https://
icon: 
keywords:
- java
maintainers:
- email: 29ygq@sina.com
  name: Chinge Yang
