apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fastdfs-nginx.fullname" . }}
  labels:
    app: {{ template "fastdfs-nginx.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
{{ toYaml .Values.fastdfs.tracker.configFiles | indent 2 }}
