apiVersion: v1
kind: Service
metadata:
  name: {{ template "fastdfs-nginx.fullname" . }}-tracker
  labels:
    app: {{ template "fastdfs-nginx.name" . }}
    chart: {{ template "fastdfs-nginx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: tracker
      port: {{ .Values.service.port.tracker }}
      protocol: TCP
      targetPort: tracker
    - name: tracker-nginx
      port: {{ .Values.service.port.trackerNginx }}
      protocol: TCP
      targetPort: tracker-nginx
  selector:
    app: {{ template "fastdfs-nginx.name" . }}
    release: {{ .Release.Name }}
