{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ default .Values.service.name (include "utcook.fullname" .) }}
  labels:
    app: {{ template "utcook.name" . }}
    chart: {{ template "utcook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  # trafficPolicy:
  #   tls:
  #     mode: ISTIO_MUTUAL
  host: {{ default .Values.service.name (include "utcook.fullname" .) }}
  subsets:
  - name: default
    labels:
      canary: "false"
      app: {{ template "utcook.name" . }}
      release: {{ .Release.Name }}
      version: {{ template "utcook.version" . }}
  {{- range $skey, $svalue := .Values.istio.canary }}
  - name: {{ $svalue.name }}
    labels:
      canary: "true"
      app: {{ template "utcook.name" $ }}
      release: {{ $.Release.Name }}
      version: {{ $svalue.image.tag }}
  {{- end }}
{{- end -}}
